### ISSUE TITLE
brl.mod/dxgraphics.mod does not compile

### ISSUE THREAD

**Issue by xlsior75** [maxmods/brl.mod#24]
Latest bmk/bcc, dxgraphics.mod does not compile:

[  8%] Processing:d3d9graphics.bmx
[  8%] Processing:source.bmx
Compile Error: Can't create instance of type TD3D9Graphics due to abstract Method TGraphics.Resize:Int(width:Int,height:Int).
[c:/code/BlitzmaxNG810/mod/brl.mod/dxgraphics.mod/d3d9graphics.bmx;162;0]
Build Error: failed to compile (-1) c:/code/BlitzmaxNG810/mod/brl.mod/dxgraphics.mod/d3d9graphics.bm

**Comment by GWRon** [comment]
Wrong repository ;-)
