### ISSUE TITLE
BRL.graphics() windows position

### ISSUE THREAD

**Issue by MidimasterSoft** [maxmods/brl.mod#31]
In the current version (BCC 0.136, BMK 3.51, downloaded 2 days ago: 2023/04/05)  in windows 10 this code runs into a bug:
``` SuperStrict
Graphics 800,600,,,,600,200
Global currDriver:TGraphicsDriver= GetGraphicsDriver()
Print currDriver.ToString()
Repeat

Until AppTerminate()
______________
returns: OPENGL 
 ```
no framework, no changes, only using the default settings of Blitzmax....

The window opens, the windows-Position uses the Y-value, but the X-value is ignored. So the window starts at the very left screen border (here: at 0,200)

**Comment by GWRon** [comment]
@woollybah This issue needs to be moved to https://github.com/bmx-ng/brl.mod



Regarding issue: Can verify it for brl.GLMax2D
brl.d3d9max2d works

**Comment by GWRon** [comment]
Ah ok ... there is a parameter wrong in 
`BBGLContext *bbGLGraphicsCreateGraphics( int width,int height,int depth,int hertz, int flags, int x, int y ){`

flags must be BBInt64
